// Generated by PlaywrightMcpGeneratorService
// Story   : ECOM-LOGIN-001 — Customer can log in to the storefront with valid credentials
// Source  : jira/story-login.json — acceptance criteria OBJ-01 and OBJ-03
// Refactored to use Page Object Model

import path from "node:path";
import { test, expect } from "@playwright/test";

import { LoginPage } from "./pages/login.page";
import { DashboardPage } from "./pages/dashboard.page";

const BASE_URL =
  process.env["BASE_URL"] ?? "https://opensource-demo.orangehrmlive.com/";

// ---------------------------------------------------------------------------
// ECOM-LOGIN-001 — Page Object Model Tests
// ---------------------------------------------------------------------------

test.describe("ECOM-LOGIN-001", () => {
  let loginPage: LoginPage;
  let dashboardPage: DashboardPage;

  test.beforeEach(async ({ page }) => {
    loginPage = new LoginPage(page, BASE_URL);
    dashboardPage = new DashboardPage(page);
    await loginPage.goto();
    await loginPage.assertLoginPageDisplayed();
  });

  test.afterEach(async ({ page }, testInfo) => {
    if (testInfo.status !== "passed") {
      const screenshotName = `${testInfo.title.replace(/\s+/g, "-")}-failure.png`;
      await page.screenshot({
        path: path.join("screenshots", screenshotName),
        fullPage: true,
      });
    }
  });

  // ── Scenario 1 ──────────────────────────────────────────────────────
  // OBJ-01: Verify the login flow succeeds with the expected customer path
  //         when valid email and password are submitted
  // ────────────────────────────────────────────────────────────────────

  test("Verify the login flow succeeds with the expected customer path: valid email and password are submitted", async () => {
    // Given: User is on the login page
    await loginPage.assertLoginPageDisplayed();

    // When: Valid credentials are entered
    await loginPage.login("Admin", "admin123");

    // Then: User is redirected to the dashboard
    await dashboardPage.assertDashboardDisplayed();
    await dashboardPage.assertUserLoggedIn();
  });

  // ── Scenario 2 ──────────────────────────────────────────────────────
  // OBJ-03: Verify authentication failures are handled safely
  //         when incorrect credentials are provided
  // ────────────────────────────────────────────────────────────────────

  test("Verify authentication failures are handled safely: incorrect credentials", async () => {
    // Given: User is on the login page
    await loginPage.assertLoginPageDisplayed();

    // When: Incorrect password is entered
    await loginPage.login("Admin", "wrongpassword");

    // Then: An error message is displayed
    await loginPage.assertErrorDisplayed();
    const errorMsg = await loginPage.getErrorMessage();
    expect(errorMsg).toBeTruthy();
  });
});
