// Generated by PlaywrightMcpGeneratorService
// Story   : ECOM-LOGIN-001 — Customer can log in to the storefront with valid credentials
// Source  : jira/story-login.json — acceptance criteria OBJ-01 and OBJ-03
// DO NOT EDIT MANUALLY — regenerate via the generator service

import path from "node:path";

import { test, expect } from "@playwright/test";

// ---------------------------------------------------------------------------
// Shared configuration
// ---------------------------------------------------------------------------

const BASE_URL =
  process.env["BASE_URL"] ?? "https://opensource-demo.orangehrmlive.com/";

const SELECTORS = {
  usernameInput: 'input[name="username"]',
  passwordInput: 'input[name="password"]',
  submitButton: 'button[type="submit"]',
  errorAlert: ".oxd-alert-content-text",
  dashboardHeading: ".oxd-topbar-header-breadcrumb",
  userDropdown: ".oxd-userdropdown-name",
} as const;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

async function fillLoginForm(
  page: import("@playwright/test").Page,
  username: string,
  password: string,
) {
  await page.fill(SELECTORS.usernameInput, username);
  await page.fill(SELECTORS.passwordInput, password);
  await page.click(SELECTORS.submitButton);
}

// ---------------------------------------------------------------------------
// ECOM-LOGIN-001 — OBJ-01: Successful login (happy-path)
// ---------------------------------------------------------------------------

test.describe("ECOM-LOGIN-001", () => {
  test.beforeEach(async ({ page }) => {
    await page.goto(BASE_URL);
  });

  test.afterEach(async ({ page }, testInfo) => {
    if (testInfo.status !== "passed") {
      const screenshotName = `${testInfo.title.replace(/\s+/g, "-")}-failure.png`;
      await page.screenshot({
        path: path.join("screenshots", screenshotName),
        fullPage: true,
      });
    }
  });

  // -------------------------------------------------------------------------
  // Scenario 1 — Successful login with valid credentials
  // Acceptance criterion OBJ-01:
  //   Given a registered customer, when valid email and password are submitted,
  //   then the customer is signed in and redirected to the account or home page.
  // -------------------------------------------------------------------------

  test("Verify the login flow succeeds for the expected customer path: valid email and password are submitted", async ({
    page,
  }) => {
    // Given: a registered customer on the login page
    await expect(page.locator(SELECTORS.usernameInput)).toBeVisible();
    await expect(page.locator(SELECTORS.passwordInput)).toBeVisible();

    // When: valid credentials are submitted
    await fillLoginForm(page, "Admin", "admin123");

    // Then: the customer is redirected to the dashboard
    await expect(page).toHaveURL(/dashboard/i);
    await expect(page.locator(SELECTORS.dashboardHeading)).toBeVisible();
  });

  // -------------------------------------------------------------------------
  // Scenario 2 — Invalid login with wrong password
  // Acceptance criterion OBJ-03:
  //   Given incorrect credentials, when the customer attempts to sign in,
  //   then a clear authentication error is displayed without exposing sensitive
  //   details.
  // -------------------------------------------------------------------------

  test("Verify authentication failures are handled safely: incorrect credentials", async ({
    page,
  }) => {
    // Given: a registered customer on the login page
    await expect(page.locator(SELECTORS.usernameInput)).toBeVisible();
    await expect(page.locator(SELECTORS.passwordInput)).toBeVisible();

    // When: invalid credentials are submitted
    await fillLoginForm(page, "Admin", "wrongpassword");

    // Then: an authentication error is shown and the URL stays on the login page
    await expect(page.locator(SELECTORS.errorAlert)).toBeVisible();
    await expect(page.locator(SELECTORS.errorAlert)).toContainText(
      "Invalid credentials",
    );
    await expect(page).toHaveURL(/login/i);

    // And: sensitive implementation details are not exposed
    const errorText = await page.locator(SELECTORS.errorAlert).innerText();
    expect(errorText).not.toMatch(/stack|trace|exception|sql|password/i);
  });
});
